### ISSUE TITLE
Publish a pre-built Docker image

### ISSUE THREAD

**Issue by nwithan8** [TheImaginear/dynamixX#4]
Please publish a pre-built Docker image on Docker Hub or GitHub Container Registry. This is needed to allow this to be made into an Unraid Community Apps Store template.

**Comment by TheImaginear** [comment]
I promise that will be implemented either in the next day or two, or next week. I'm still learning docker so I have to look into that still.

**Comment by nwithan8** [comment]
Available to help if you want, should just be a GitHub Actions that can do it all for you. Done it before on a number of my own projects.
