### ISSUE TITLE
Docker Build- Config not being read

### ISSUE THREAD

**Issue by TylStres** [TheImaginear/dynamixX#5]
I setup the docker image and the logs are saying that it cannot resolve my plex name. I used the configexample.json to create a config.json file with the updated data and placed it in my mapped /config volume. I cant seem to find where the "generated" config file is located. Where should this file be placed in order to get it to map correctly?

**Comment by nwithan8** [comment]
The config file on your host machine needs to be mapped to `/app/config.json` inside the container.

**Comment by TheImaginear** [comment]
Exactly as described above. Thank you nwithan8! Ill be adding a docker CLI for config set-up soon.
